trigger:
- main  # Run pipeline on push to 'main' branch

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm audit fix || true  # Attempt to fix vulnerabilities; ignore errors
    npm test || echo 'No tests defined'
  displayName: 'Install Dependencies and Run Tests'

- script: |
    npm run build || echo 'No build step required'
  displayName: 'Build Backend'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'AzureForStudentsConnection'
    appType: 'webAppLinux'  # Specify that this is a Linux-based Web App
    appName: 'memowo-be'
    package: '.'
  displayName: 'Deploy Backend to Azure'

